/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.polinomioCromatico.vista;

import co.edu.polinomioCromatico.AdministradorArchivos.administradorArchivos;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Mario
 */
public class Inicio extends javax.swing.JPanel 
{
    private administradorArchivos adm;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        adm = new administradorArchivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCargarDocumento = new javax.swing.JLabel();
        botonCargarDocumento = new javax.swing.JButton();

        labelCargarDocumento.setText("Cargar documentos");

        botonCargarDocumento.setText("Cargar Documento");
        botonCargarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelCargarDocumento)
                .addGap(29, 29, 29)
                .addComponent(botonCargarDocumento)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargarDocumento)
                    .addComponent(botonCargarDocumento))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarDocumentoActionPerformed
        JFileChooser archivo =new JFileChooser();
        archivo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);        
        int result = archivo.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            File archivoLeido = archivo.getSelectedFile();
            String nombreArchivo = archivoLeido.getAbsolutePath();
            
        } 
    }//GEN-LAST:event_botonCargarDocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarDocumento;
    private javax.swing.JLabel labelCargarDocumento;
    // End of variables declaration//GEN-END:variables
}
